### ISSUE TITLE
05 - 02 - CSS all the things!

### ISSUE THREAD

**Issue by RobMack8932** [RobMack8932/assignments#17]
Now that you have created some HTML, its time to give your page some personality.

For this assignment you will be taking the HTML you made for the last project and extending it to have some styling.

### Requirements

- Apply the ideas and stylings that you learn about in class.

### Explorer Mode

- [ ] Take the CSS ideas and tools that were discussed in class and apply those to your homework.
- [ ] Apply colors, margin, padding, background colors, and font styles to the various elements of the page. Add `class=` where needed but try to keep to element selectors if you can!

### Explorer Mode

- [ ] Research fonts.google.com and find an alternative font, or two, for your site. Use two different fonts (but no more than two) to style different aspects of your page. Maybe headers in one font and text in another.

### Additional Resources

- [Cool game to learn CSS selectors](https://flukeout.github.io/)
- [Introduction to CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS)
- [Getting Started with CSS Rules](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics#Anatomy_of_a_CSS_ruleset)
- [All the CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#Keyword_index)
- [pseudo-classes and pseudo-elements](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Pseudo-classes_and_pseudo-elements)
- [http://www.csszengarden.com/](http://www.csszengarden.com/)

**Comment by RobMack8932** [comment]
https://hello-world-robma.netlify.com

**Comment by gstark** [comment]
NIcely done!

Your header is hard to read since it is black text on a dark background. Revise it and give it a lighter text color and redeploy!

**Comment by RobMack8932** [comment]
Your homework **05 - 02 - CSS all the things!** was marked: **Meets Expectations**


![With LASERS](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8de0b77cb9bd24d453ed6e604c00bc8768a57d5c/BriskEnviousGraywolf.gif)
> &ldquo;With LASERS&rdquo;

**Comment by RobMack8932** [comment]
https://hello-world-robma.netlify.app/
