### ISSUE TITLE
06 - 01 - console.log('Welcome to JavaScript')

### ISSUE THREAD

**Issue by RobMack8932** [RobMack8932/assignments#20]
# Let's get started

Today, we are starting our journey into JavaScript. For this assignment, you
will be making a program that demonstrates some JavaScript fundamentals.

## Objectives

- Ensure your development environment is setup
- Practice creating variables
- Practice working with user input

## Requirements

Create your project using `app-app` with the `beta` stack

Remove all the code inside `main.js` and start with a fresh and empty file.

### Explorer Mode

- [ ] Create a new app that does the following.

  - Practice Creating Variables

    - Create a variable that stores the `numberOfCupsOfCoffee` that you drink every day (even if that is zero).
    - Create a variable called `fullName` and set it equal to your full name.
    - Use `console.log` and your variables, `numberOfCupsOfCoffee` and `fullName` to output all three on one line.

  - Practice Getting Input From the User

    - Ask the user for their name and store it in a variable named `userName`. (use `window.prompt` to get input from the user)
    - Console log a greeting to the user, using their name.

  - Converting String Input Into Numbers

    - Input two numbers from the user. Use `window.prompt` twice, once for each prompt/number. Convert each resulting `string` from `window.prompt` to a `float` using [parseFloat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat). Save the first value in a variable named `firstOperand` and the second value in a variable named `secondOperand`.
  - Doing Math

    - Add the operand variables from above and save the results in a variable named `sum`.
    - Subtract the `secondOperand` variable from the `firstOperand` variable and 
 save the results in a variable named `difference`.
    - Multiply the operand variables and save the results in a variable named
 `product`.
    - Divide the `firstOperand` by the `secondOperand` and save the results in a
      variable named `quotient`.
    - Find the remainder when one operand is divided by the other and save the results in a variable named `remainder`.
    - Use `console.log` to present the user, in a meaningful way, each of the values for the `sum`, `difference`, `quotient`, `product`, and `remainder` variables. (e.g. perhaps one of your outputs is similar to
      `If you add 4 and 5 you get 9` if `4` and `5` were the input)

  - Using Arrays

    - Use
      [this page](https://www.random.org/integers/?num=100&min=1&max=100&col=5&base=10&format=plain&rnd=new) to generate a array of random numbers.
    - Place these numbers into a properly formatted array named `numbers`.
    - Determine the following. Use JavaScripts `for` loops to your advantage.
      - In a variable named `smallest`, find the smallest value in the array
      - In a variable named `largest`, find the largest value in the array
      - In a variable named `sum`, find the sum of all the values in the array
      - In a variable named `average`, find the average of all the values in the
        array

### Adventure Mode

- Revisit your arrays. This time create new variables that represent:
  - `sumOfOdd` that contains the sum of all the odd numbers
  - `countOfEven` that contains the total count of all the even numbers

**Comment by RobMack8932** [comment]
// Name and coffee amount

const fullName = 'Rob Mack'
const numberOfCupsOfCoffee = 2
console.log(
  `Hey my name is ${fullName} and I drink ${numberOfCupsOfCoffee} cups of coffee a day!`
)
// User name
const userName = window.prompt('What is your name?')
console.log(`Hey there ${userName}`)
// Input Numbers
const firstOperand = window.prompt('Give me a number any number!')
console.log(`Okay, ${firstOperand} it is!`)
parseFloat(firstOperand)
const secondOperand = window.prompt('I lied, one more..!')
console.log(`Okay, ${secondOperand} it is!`)
parseFloat(secondOperand)
//Math
const sum = +firstOperand + +secondOperand
console.log(
  `If you add ${firstOperand} and ${secondOperand} you will get ${sum}`
)
//subtract
const difference = firstOperand - secondOperand
console.log(
  `If you subtract ${firstOperand} by ${secondOperand} you will get ${difference}`
)
//multiply
const product = firstOperand * secondOperand
console.log(
  `If you multiply ${firstOperand} and ${secondOperand} you will get ${product}`
)
//divide
const quotient = firstOperand / secondOperand
console.log(
  `If you divide ${firstOperand} by ${secondOperand} you will get ${quotient}`
)
//arrays

const numbers = [
  61,
  41,
  65,
  21,
  44,
  98,
  20,
  32,
  54,
  49,
  84,
  74,
  16,
  59,
  5,
  12,
  44,
  31,
  52,
  78,
  66,
  10,
  48,
  17,
  33,
  39,
  20,
  9,
  61,
  66,
  56,
  36,
  25,
  75,
  69,
  77,
  2,
  7,
  87,
  63,
  15,
  66,
  37,
  81,
  33,
  74,
  71,
  52,
  89,
  58,
  27,
  93,
  80,
  95,
  16,
  50,
  72,
  18,
  77,
  88,
  34,
  20,
  56,
  18,
  66,
  43,
  34,
  31,
  11,
  77,
  8,
  31,
  100,
  12,
  83,
  96,
  21,
  31,
  17,
  24,
  77,
  78,
  70,
  85,
  7,
  59,
  5,
  12,
  76,
  5,
  21,
  73,
  3,
  38,
  28,
  70,
  68,
  90,
  34,
  42,
]
const smallest = numbers[0]
console.log(smallest)



Hey Gavin I couldn't git push this one so I just wanted to copy and paste it, been stumped on the arrays for awhile so

**Comment by RobMack8932** [comment]
Your homework **06 - 01 - console.log('Welcome to JavaScript')** was marked: **Acceptable**


![Hmm ok ](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a5311edd7d489ed156ec6b740b1cfac394c2c264/unicorn%20pug.gif)
> &ldquo;Hmm ok &rdquo;

**Comment by gstark** [comment]
See if you can work with Jordan and get this in a repository and work on the array part. I'm going to mark this as acceptable, but I think it is a good assignment to revisit later.
