### ISSUE TITLE
01 - 03 - All Cards On Deck

### ISSUE THREAD

**Issue by RobMack8932** [RobMack8932/assignments#3]
In this project, you will use C# to model [a deck of playing cards](https://en.wikipedia.org/wiki/standard_52-card_deck). You'll also add functionality such as shuffling and dealing.

### Shuffling Cards

As we have seen, computers do _exactly_ what we tell them to do. Thus, computers are bad at generating truly random numbers. Randomness is a deep and complex topic, but it's worth pointing out that most random numbers we use in computing are what we call "[pseudorandom](https://en.wikipedia.org/wiki/pseudorandomness)". That is, they generate numbers that appear to be random such that _guessing_ the next random number the computer's fixed algorithm is going to generate is very difficult. This makes it _good enough_ for most purposes. For this assignment, you will read about, then implement, a popular algorithm that shuffles the order of a finite set using C#'s built-in `Random.Next()` function as a pseudorandom number generator.

## Objectives

- Demonstrate usage of arrays to model resources.
- Understand and implement algorithms.
- Understand loops.

## Requirements

- Your deck should contain 52 unique cards.
- All cards should be represented as as string such as "Ace of Hearts"
- There are four suits: "Clubs", "Diamonds", "Hearts", and "Spades".
- There are 13 ranks: "Ace", "2", "3", "4", "5", "6", "7", "8", "9", "10",
  "Jack", "Queen", and "King".

You will model these in code, in any way you see fit. It may require you to experiment and try several techniques. There are _many_ valid solutions.

> NOTE: The more you plan this out (focus on the _algorithm_) the better you will do.

To shuffle the cards, you should implement the [Fisher–Yates shuffle](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle) algorithm. The shuffling algorithm starts with the last element in our collection (in our case a deck of cards) and swaps it with a randomly selected element that comes before it. This continues downward through the elements towards the first element. Watch the first few minutes [of this video](https://www.youtube.com/watch?v=tLxBwSL3lPQ) for a visual description of the algorithm.

If we were going to write an _algorithm_ for this we would write something like:

```
make n = 52 since we are dealing with 52 elements

for firstIndex from n - 1 down to 1 do:
  secondIndex = random integer that is greater than or equal to 0 and LESS than firstIndex

  Now swap the values at firstIndex and secondIndex by doing this:
    firstValue = the value from items[firstIndex]
    secondValue = the value from items[secondIndex]
    items[firstIndex] = secondValue
    items[secondIndex] = firstValue
```

_hint:_ understand the algorithm before you try to implement it.

### Explorer Mode

- [ ] Once the program starts, you should create a new deck.
- [ ] After deck creation, you should shuffle the deck.
- [ ] After the deck is shuffled, display the top two cards.

## Adventure Mode

- [ ] In addition to displaying the top two cards, also store these two "dealt" cards in a variable named `playerHand`. Consider what _type_ of variable `playerHand` will have to be.
- [ ] Implement a way to deal cards into two _different_ hands.

## Epic Mode

- [ ] Implement the game of [War][1]

[1]: https://en.wikipedia.org/wiki/War_(card_game)

## Resources

- [List](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=netcore-3.1)

**Comment by RobMack8932** [comment]
using System;
using System.Collections.Generic;
using System.Linq;



namespace Cards
{
    class Program
    {

        static void Main(string[] args)
        {

            Random rnd = new Random();
            var deck1 = new List<string>() { "Ace of Spades", "Ace of Hearts", "Ace of Diamonds", "Ace of Clubs", "Two of Spades", "Two of Hearts", "Two of Diamonds", "Two of Clubs", "Three of Spades", "Three of Hearts", "Three of Diamonds", "Three of Clubs", "Four of Spades", "Four of Hearts", "Four of Diamonds", "Four of Clubs", "Five of Spades", "Five of Hearts", "Five of Diamonds", "Five of Clubs", "Six of Spades", "Six of Hearts", "Six of Diamonds", "Six of Diamonds", "Seven of Spades", "Seven of Hearts", "Seven of Diamonds", "Seven of Clubs", "Eight of Spades", "Eight of Hearts", "Eight of Diamonds", "Eight of Clubs", "Nine of Spades", "Nine of Hearts", "Nine of Diamonds", "Nine of Clubs", "Ten of Spades", "Ten of Hearts", "Ten of Diamonds", "Ten of Clubs", "Jack of Spades", "Jack of Hearts", "Jack of Diamonds", "Jack of Clubs", "Queen of Spades", "Queen of Hearts", "Queen of Diamonds", "Queen of Clubs", "King of Spades", "King of Hearts", "King of Diamonds", "King of Clubs" };
            Console.WriteLine("Hit Enter To Shuffle Deck and Reveal Two Cards");
            Console.ReadLine();

            for (int firstIndex = deck1.Count - 1; firstIndex >= 0; firstIndex--)
            {
                int secondIndex = rnd.Next(0, firstIndex);
                var firstValue = deck1[firstIndex];
                deck1[firstIndex] = deck1[secondIndex];
                deck1[secondIndex] = firstValue;
            }
            Console.WriteLine(deck1[0]);
            Console.WriteLine(deck1[1]);
        }
    }
}

**Comment by gstark** [comment]
Hi Robert, nicely done. I'm going to close and accept this, but please post just a *github link* to your repository. It should look like  `https://github.com/RobMack8932/xxxxxxxxxx`

**Comment by RobMack8932** [comment]
Your homework **01 - 03 - All Cards On Deck** was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5adeb8e5322994e0cbd1bcd7685cf653f71d406a/giphy-8.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/73)**__
