### ISSUE TITLE
01 - 04 - Blackjack

### ISSUE THREAD

**Issue by RobMack8932** [RobMack8932/assignments#4]
In this project, you are creating a playable game of
[Blackjack](https://en.wikipedia.org/wiki/Blackjack). If you haven't played this
game ever, or in a while, grab a deck of cards and play a few games.

## Objectives

- Practice the skills and ideas you have learned so far.
- Effectively use loops, conditionals, and other control structures to implement
  [control flows](https://en.wikipedia.org/wiki/Control_flow)
- Demonstrate usage of data structures to model resources.

## Requirements

Create a single-player blackjack game that plays against the house, i.e., a
human player and computer dealer. You are free to create the user interface
however you want, **but keep it simple for Explorer Mode**.

### Explorer Mode

General Rules:

- [ ] The game should be played with a standard deck of playing cards (52).
- [ ] The house should be dealt two cards, hidden from the player until the
      house reveals its hand.
- [ ] The player should be dealt two cards, visible to the player.
- [ ] The player should have a chance to hit (i.e. be dealt another card) until
      they decide to stop or they _bust_ (i.e. their total is over 21). At which
      point they lose regardless of the dealer's hand.
- [ ] When the player stands, the house reveals its hand and hits (i.e. draw
      cards) until they have 17 or more.
- [ ] If dealer goes over 21 the dealer loses.

- [ ] The player should have two choices: "Hit" and "Stand."
- [ ] Consider Aces to be worth 11, never 1.
- [ ] The app should display the winner. For this mode, the winner is who is
      closer to a blackjack (21) without going over.
- [ ] There should be an option to play again; this should reset the hands and
      reshuffle the deck.

### Adventure Mode

- [ ] Reveal one of the house's cards to the player when cards dealt.
- [ ] Consider aces be worth one _or_ eleven.
- [ ] Allow the player to
      ["Split"](https://blog.betway.com/casino/blackjack-strategy-101-how-do-you-split-in-blackjack/).
- [ ] Improve the win requirements. From Wikipedia:
  > Players win by not busting and having a total higher than the dealer, or not
  > busting and having the dealer bust, or getting a blackjack without the
  > dealer getting a blackjack. If the player and dealer have the same total
  > (not counting blackjacks), this is called a "push," and the player typically
  > does not win or lose money on that hand. Otherwise, the dealer wins.

### Epic Mode

- [ ] Add a betting system that carries between rounds.
- [ ] Allow the player to "Double down" or "Surrender."
- [ ] Add more players.

**Comment by RobMack8932** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace BlackJackFinal
{
    class Program
    {
        static void Main(string[] args)
        {

            int playerCardValue = 0;
            int dealerCardValue = 0;

            switch (cardValue)
            {
                case 1:
                    Console.WriteLine("Ace Card");
                    break;
                case 2:
                    Console.WriteLine("2 Card");
                    break;
                case 3:
                    Console.WriteLine("4 card");
                    break;
                case 5:
                    Console.WriteLine("5 card");
                case 6:
                    Console.WriteLine("6 card");
                    break;
                case 7:
                    Console.WriteLine("7 card");
                    break;
                case 8:
                    Console.WriteLine("8 card");
                    break;
                case 9:
                    Console.WriteLine("9 Card");
                    break;
                case 10:
                    Console.WriteLine("10, Jack, Queen, King");
                    break;
            }



        }

        //Random Number from deck because of card value
        Random random = new Random();

        playerCardValue += random.Next(1, 12);
            playerCardValue += random.Next(1, 12);

            if (playerCardValue > 21)
            {
                playerCardValue -= 10;
            }

    dealerCardValue += random.Next(1, 12);
            dealerCardValue += random.Next(1, 12);

            //So no one busts

            if (dealerCardValue > 21)
            {
                dealerCardValue -= 10;

            }
            //Player

            while (true)
            {
                if (playerCardValue == 21)
                {
                    Console.WriteLine("Congrats on 21!");
                    break;

                }
                Console.WriteLine("Your Card Value: " + playerCardValue.ToString() + "Hit again?");


                string answer = Console.ReadLine();
                if (answer == "y")
                {
                    //To hit again
                    playerCardValue += random.Next(1, 12);

                    if (playerCardValue > 21)
                    {
                        Console.WriteLine("You've gone over 21");
                        break;

                    }
                    else
                    {
                        continue;
                    }
                }
                else if (answer == "n")
                {
                    break;

                }
                else
                {
                    Console.WriteLine("Try Again");
                    //Continue will continue loop
                    continue;
                }

            }

            //Dealer
            Console.WriteLine("Players Card Value is " + playersCardValue.ToString());

            if (playerCardValue <= 21)
            {
                while (dealerCardValue< 21 && dealersCardValue<playerCardValue)
                {
                    dealerCardValue += random.Next(1, 12);
                }

                //Check For Winner
                if (playerCardValue == dealerCardValue)
                {
                    Console.WriteLine("Player and Dealer have tied");
                }

                else if (playerCardValue<dealerCardValue && dealerCardValue <= 21)
                {
                    Console.WriteLine("The Dealer Has Won");
                }
                else if (dearlersCardValue > 21)
                {
                    Console.WriteLine("Dealer has busted, You've won!");
                }

                else if (dealersCardValue == 21)
                {
                    Console.WriteLine("The dealer has won :(");

                }

            }
            else
            {
                Console.WriteLine("Dealer has won the game");
            }
            


        }
    }
}

**Comment by RobMack8932** [comment]
Not finished, need help loading it in a browser, sorry about just sending the code.

**Comment by gstark** [comment]
Rob, I'm going to reopen this homework, please just send me the github link to your *repository*

It should look like `https://github.com/RobMack8932/xxxxxxx` where `xxxxxxx` is the name of the repository.

**Comment by RobMack8932** [comment]
Your homework **01 - 04 - Blackjack** was marked: **Needs Improvement**

![Keep rolling with it](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBHZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1a5861defaf25697d82b847afc71ef4a7637666f/chihuaha.gif)
> &ldquo;Keep rolling with it&rdquo;
__&mdash; via **[Katherine Trammell](https://gifs.suncoast.io/venerations/16)**__

**Comment by RobMack8932** [comment]
https://github.com/RobMack8932/BlackJackFinal

**Comment by RobMack8932** [comment]
Your homework **01 - 04 - Blackjack** was marked: **Unacceptable**


![Unacceptable](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ec680330d01374698015cbe23fee13bccca8f355/greenColaNo.gif)
> &ldquo;Unacceptable&rdquo;

**Comment by gstark** [comment]
Hi Rob, I cannot accept this code as is, it does not run when I execute `dotnet run`

I'd like you to schedule some lab time with Jordan to review some basics and go through the Blackjack assignment as an example. Work together with him to do so.

**Comment by RobMack8932** [comment]
https://github.com/RobMack8932/BJack

**Comment by RobMack8932** [comment]
Your homework **01 - 04 - Blackjack** was marked: **Acceptable**


![hmmm..acceptable! ](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBSZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dbf0839075b0c873bc9d53d1b39f6ae9204934b9/acceptable.gif)
> &ldquo;hmmm..acceptable! &rdquo;

**Comment by gstark** [comment]
Hi Rob, I'm going to accept this assignment but acknowledge that you copied this code directly from the code review I did. While I appreciate you completing the assignment I feel you are shortchanging **yourself** by not reimplementing it on your own.

I'm marking this assignment "acceptable" and I strongly encourage you to implement and turn in your own work products in the future.
